### ISSUE TITLE
Fix/SWOT resolution data

### ISSUE THREAD

**Issue by jbyrne6** [podaac/hitide-ui#33]
SWOT resolution data is under two resolutions so it is not displaying correctly when clicking the info button for the collection in hitide ui.

**Comment by davidcolemanjpl** [comment]
Please define the fix / expected results for this ticket. 

Was this fix related to all SWOT collection in UI?

**Comment by davidcolemanjpl** [comment]
**_HiTIDE-UI (UAT) v4.16.1rc1_**

**_Test Complete_**

Reviewed the following SWOT_L2 cloud collections in HiTIDE UAT env:

SWOT_L2_LR_SSH_1.1 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_BASIC_1.0 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_BASIC_1.1 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_EXPERT_1.0 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_EXPERT_1.1 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_UNSMOOTHED_1.0 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_UNSMOOTHED_1.1 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_WINDWAVE_1.0 –
Spatial Resolution      2km x 2km and 250m x 250m

SWOT_L2_LR_SSH_WINDWAVE_1.1 –
Spatial Resolution      2km x 2km and 250m x 250m



This issue is related to 
https://github.com/podaac/hitide-ui/pull/34
